### ISSUE TITLE
Code Clean up & Comments on details of async functions

### ISSUE THREAD

**Issue by pgorripati1** [Dari-Jones/dndfront#1]
Please remove commented code & add more details on the data functions about the purpose of them.

https://github.com/Dari-Jones/dndfront/blob/fd4d19cdde3e0e6c9dee65fc0858a3386c5ef6c0/src/app/services/generator.service.ts#L10

https://github.com/Dari-Jones/dndfront/blob/fd4d19cdde3e0e6c9dee65fc0858a3386c5ef6c0/src/app/services/generator.service.ts#L13

https://github.com/Dari-Jones/dndfront/blob/fd4d19cdde3e0e6c9dee65fc0858a3386c5ef6c0/src/app/services/generator.service.ts#L32-L36

https://github.com/Dari-Jones/dndfront/blob/fd4d19cdde3e0e6c9dee65fc0858a3386c5ef6c0/src/app/services/generator.service.ts#L37-L40

https://github.com/Dari-Jones/dndfront/blob/fd4d19cdde3e0e6c9dee65fc0858a3386c5ef6c0/src/app/services/generator.service.ts#L41-L44

https://github.com/Dari-Jones/dndfront/blob/fd4d19cdde3e0e6c9dee65fc0858a3386c5ef6c0/src/app/services/generator.service.ts#L45-L48

https://github.com/Dari-Jones/dndfront/blob/fd4d19cdde3e0e6c9dee65fc0858a3386c5ef6c0/src/app/services/generator.service.ts#L49-L52

**Comment by Dari-Jones** [comment]
Updated comments to address issue.
